### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by debayan** [xgfs/deepwalk-c#12]
When constructing the HSM tree I face a segmentation fault. Here is the bcsr file that is the input. 1.9 GB download  https://uni-bonn.sciebo.de/s/K9ECnxo1Z9sIHe6

**Comment by xgfs** [comment]
It seems that several things are happening:

1. As the graph has several sink nodes with > 1m edges each, not every node get a positive weight for HSM tree construction.
2. The HSM tree total size was an int mindlessly, this would always fail in case the tree is more than 2GB in size.

The problem with segfault persists as some of hsm_ptrs are out of range, I will investigate it further.

**Comment by debayan** [comment]
Thanks a lot for looking into this.

**Comment by debayan** [comment]
Just fyi, I am trying to create embeddings for wikidata.

**Comment by xgfs** [comment]
Some post-mortem: there were actually 3 bugs that you were able to expose with the single dataset - quite an achievement!

First, the overflow would occur if the embedding size is more than 4GB. This was happening because the array offset [was an int](https://github.com/xgfs/deepwalk-c/commit/579929b54b4b89b0241a99ce70d3b6fdf68b0e88#diff-8bfe2a0b58c2b7cca32840c2cc8d69b2L436-R443).

Second, the size of the hierarchical softmax tree was exceeding 4GB limit as well, so I had to convert pointers to be 64 bit as well and change some minor HSM construction logic.

Third, as your graph has some serious imbalance issues, some nodes were never visited during the random walks, and were getting an HSM weight of 0. This is fixed now.

If you see any more issues feel free to reopen.

**Comment by debayan** [comment]
Thanks, the training does proceed beyond where it was freezing before. Do you have plans to add GPU support?

**Comment by xgfs** [comment]
This is intended to be an as-optimized-as-it-gets implementation that is close to the original DeepWalk (and reproduces their results). There is a possibility of speeding it up even further, but that would break compatibility and will only be est. 2x-4x faster.

The nature of the algorithm does not really work too well for GPUs - it requires a lot of random memory accesses, and they are very expensive on GPUs. There is research on doing embeddings on GPUs - check out [graphvite.io](https://graphvite.io/) for that.

Besides, I'm simply not a CUDA programmer. :)
